version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.2
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/base-12-14-0
          # we need to start the web application
          start: npm start
          wait-on: "http://localhost:3000"
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            # fail step if the coverage drops below 100%
            - run: npx nyc report --check-coverage --statements 100
            - run: |
                npx check-coverage App.js
                npx check-coverage index.js
                npx only-covered --from coverage/coverage-final.json App.js index.js
            # publish new version if necessary
            - run: npm run semantic-release

