version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      # install and cache dependencies in this job
      # AND build the library once
      # then the workspace will be passed to other jobs
      - cypress/install:
          name: Install
          executor: cypress/base-12-14-0
          # creates cypress-instrument-cra-0.0.0-development.tgz file
          # then saves everything in the workspace
          build: |
            npm pack

      - cypress/run:
          name: Root tests
          requires:
            - Install
          executor: cypress/base-12-14-0
          install-command: echo 'Nothing to install in this job'
          # we need to start the web application
          start: npm start
          wait-on: "http://localhost:3000"
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            # fail step if the coverage drops below 100%
            - run: npx nyc report --check-coverage --statements 100
            - run: |
                npx check-coverage App.js
                npx check-coverage index.js
                npx only-covered --from coverage/coverage-final.json App.js index.js
            # publish new version if necessary
            - run: npm run semantic-release


      - cypress/run:
          name: react-scripts v3
          requires:
            - Install
          executor: cypress/base-12-14-0
          working_directory: examples/react-scripts-v3
          install-command: |
            ls -la ../..
            echo ***Installing package from the root TGZ archive***
            npm install -D ../../cypress-instrument-cra-0.0.0-development.tgz
            echo ***Installing other dependencies***
            npm install
            echo ***rename root node_modules to avoid accidental dependencies***
            mv ../../node_modules ../../no_modules
          verify-command: echo 'Already verified'
          # we need to start the web application
          start: npm start
          wait-on: "http://localhost:3000"
          command: npm test
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true

      # this job attaches the workspace left by the install job
      # so it is ready to run Cypress tests
      # only we will run semantic release script instead
      - cypress/run:
          name: NPM release
          # only run NPM release from specific branch(es)
          filters:
            branches:
              only:
                - master
          # we need newer Node for semantic release
          executor: cypress/base-12-14-0
          requires:
            - Install
            - Root tests
            - react-scripts v3
          install-command: echo 'Already installed'
          verify-command: echo 'Already verified'
          no-workspace: true
          command: npm run semantic-release
